# Generated by Django 4.2.3 on 2023-07-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
