# Generated by Django 4.2.3 on 2023-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="unsubscribed",
            field=models.BooleanField(default=False),
        ),
    ]
