# Generated by Django 4.2.11 on 2024-06-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_rename_jobs_post_titles'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='index_company_name',
            old_name='jobs_compan_name_2a74f5_idx',
        ),
        migrations.RenameIndex(
            model_name='technology',
            new_name='index_t_technology_name',
            old_name='jobs_techno_name_62fe8f_idx',
        ),
        migrations.RenameIndex(
            model_name='title',
            new_name='index_title_title_name',
            old_name='jobs_title_name_a1cb71_idx',
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['emails'], name='index_company_emails'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_homepage_link'], name='index_company_homepage_link'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email'], name='index_email'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email_is_valid', 'email_is_generic', 'is_approved'], name='index_email_flags'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['who_is_hiring_comment_id'], name='index_who_is_hiring_comment_id'),
        ),
        migrations.AddIndex(
            model_name='posttechnology',
            index=models.Index(fields=['post_id', 'technology_id'], name='index_post_id_technology_id'),
        ),
        migrations.AddIndex(
            model_name='posttechnology',
            index=models.Index(fields=['technology_id'], name='index_pt_technology_id'),
        ),
        migrations.AddIndex(
            model_name='posttitle',
            index=models.Index(fields=['post_id', 'title_id'], name='index_post_id_title_id'),
        ),
        migrations.AddIndex(
            model_name='posttitle',
            index=models.Index(fields=['title_id'], name='index_posttitle_title_id'),
        ),
        migrations.AddIndex(
            model_name='technology',
            index=models.Index(fields=['id'], name='index_t_technology_id'),
        ),
        migrations.AddIndex(
            model_name='technologymapping',
            index=models.Index(fields=['child_id'], name='index_child_id'),
        ),
        migrations.AddIndex(
            model_name='technologymapping',
            index=models.Index(fields=['parent_id'], name='index_parent_id'),
        ),
        migrations.AddIndex(
            model_name='technologymapping',
            index=models.Index(fields=['child_id', 'parent_id'], name='index_child_id_parent_id'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['id'], name='index_title_title_id'),
        ),
    ]
