# Generated by Django 5.2.7 on 2025-10-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_alter_post_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='technology',
            index=models.Index(fields=['slug'], name='index_t_technology_slug'),
        ),
    ]
