# Generated by Django 5.2.7 on 2025-11-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_technology_index_t_technology_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='sponsored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
