# Generated by Django 5.2.7 on 2025-11-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_post_sponsored_post_sponsored_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sponsorship_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='sponsorship_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
