# Generated by Django 5.2.7 on 2025-11-04 22:53

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_email_sponsorship_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('Sponsorship Outreach', 'Sponsorship Outreach'), ('Alert Confirmation', 'Alert Confirmation')], max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient_email', 'email_type'], name='index_recipient_type')],
                'unique_together': {('recipient_email', 'email_type')},
            },
        ),
    ]
