# Generated by Codex on 2026-06-04

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0036_add_we_work_remotely_post_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnologyAlias",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("alias", models.CharField(max_length=256)),
                ("normalized_alias", models.CharField(max_length=256, unique=True)),
                ("source", models.CharField(default="manual", max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="jobs.technology",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="technologyalias",
            index=models.Index(fields=["technology"], name="index_t_alias_technology"),
        ),
    ]
