"""
Django settings for hn_jobs project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import logging
import os
from functools import partial
from pathlib import Path

import environ
import logfire
import sentry_sdk
import structlog
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from hn_jobs.settings.observability import (
    build_posthog_span_processor,
    configure_ai_capture_content,
    configure_posthog_ai_observability,
    configure_posthog_client,
    configure_posthog_logs,
    instrument_openai,
)
from structlog_sentry import SentryProcessor

from hn_jobs.settings.logging_utils import (
    enrich_sentry_log,
    enrich_sentry_metric,
    scrubbing_callback,
    send_structlog_to_sentry,
)

BASE_DIR = Path(__file__).resolve().parent.parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

env = environ.Env(
    DEBUG=(bool, False),
)

ENVIRONMENT = env("ENVIRONMENT")
SITE_URL = env("SITE_URL", default="https://gettjalerts.com").rstrip("/")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

SENTRY_DSN = env("SENTRY_DSN", default="")
SENTRY_RELEASE = env("SENTRY_RELEASE", default="")
SENTRY_SEND_DEFAULT_PII = env.bool("SENTRY_SEND_DEFAULT_PII", default=False)
SENTRY_TRACES_SAMPLE_RATE = env.float("SENTRY_TRACES_SAMPLE_RATE", default=1.0)
SENTRY_PROFILE_SESSION_SAMPLE_RATE = env.float(
    "SENTRY_PROFILE_SESSION_SAMPLE_RATE",
    default=1.0,
)
SENTRY_ENABLE_LOGS = env.bool("SENTRY_ENABLE_LOGS", default=True)
SENTRY_ENABLE_METRICS = env.bool("SENTRY_ENABLE_METRICS", default=True)
SENTRY_LOG_LEVELS = {
    "DEBUG": logging.DEBUG,
    "INFO": logging.INFO,
    "WARNING": logging.WARNING,
    "ERROR": logging.ERROR,
    "CRITICAL": logging.CRITICAL,
}
SENTRY_LOG_LEVEL = SENTRY_LOG_LEVELS.get(env("SENTRY_LOG_LEVEL", default="INFO").upper(), logging.INFO)

SENTRY_ENABLE_BROWSER = env.bool("SENTRY_ENABLE_BROWSER", default=True)
SENTRY_BROWSER_DSN = env("SENTRY_BROWSER_DSN", default=SENTRY_DSN)
SENTRY_BROWSER_TRACES_SAMPLE_RATE = env.float(
    "SENTRY_BROWSER_TRACES_SAMPLE_RATE",
    default=SENTRY_TRACES_SAMPLE_RATE,
)
SENTRY_BROWSER_REPLAYS_SESSION_SAMPLE_RATE = env.float(
    "SENTRY_BROWSER_REPLAYS_SESSION_SAMPLE_RATE",
    default=1.0,
)
SENTRY_BROWSER_REPLAYS_ON_ERROR_SAMPLE_RATE = env.float("SENTRY_BROWSER_REPLAYS_ON_ERROR_SAMPLE_RATE", default=1.0)

LOGFIRE_TOKEN = env("LOGFIRE_TOKEN", default="")

SECRET_KEY = env("SECRET_KEY")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS")

DEBUG = env("DEBUG")

POSTHOG_API_KEY = env("POSTHOG_API_KEY", default="")
POSTHOG_HOST = env("POSTHOG_HOST", default="https://us.posthog.com").rstrip("/")
POSTHOG_INGEST_HOST = env("POSTHOG_INGEST_HOST", default="https://us.i.posthog.com").rstrip("/")
POSTHOG_ENABLED = env.bool("POSTHOG_ENABLED", default=bool(POSTHOG_API_KEY) and not DEBUG)
POSTHOG_AI_OBSERVABILITY_ENABLED = env.bool(
    "POSTHOG_AI_OBSERVABILITY_ENABLED",
    default=POSTHOG_ENABLED,
)
POSTHOG_AI_CAPTURE_CONTENT = env.bool("POSTHOG_AI_CAPTURE_CONTENT", default=False)
POSTHOG_LOGS_ENABLED = env.bool("POSTHOG_LOGS_ENABLED", default=POSTHOG_ENABLED)
POSTHOG_LOG_LEVEL = env("POSTHOG_LOG_LEVEL", default="INFO")
POSTHOG_LOG_TIMEOUT_SECONDS = env.float("POSTHOG_LOG_TIMEOUT_SECONDS", default=10)
POSTHOG_MW_CAPTURE_EXCEPTIONS = env.bool("POSTHOG_MW_CAPTURE_EXCEPTIONS", default=POSTHOG_ENABLED)

configure_posthog_client(
    api_key=POSTHOG_API_KEY,
    host=POSTHOG_INGEST_HOST,
    enabled=POSTHOG_ENABLED,
    debug=DEBUG,
)
configure_ai_capture_content(POSTHOG_AI_CAPTURE_CONTENT)

posthog_span_processor = None
if LOGFIRE_TOKEN:
    if POSTHOG_AI_OBSERVABILITY_ENABLED:
        posthog_span_processor = build_posthog_span_processor(
            api_key=POSTHOG_API_KEY,
            ingest_host=POSTHOG_INGEST_HOST,
        )

    logfire.configure(
        environment=ENVIRONMENT,
        scrubbing=logfire.ScrubbingOptions(callback=scrubbing_callback),
        additional_span_processors=[posthog_span_processor] if posthog_span_processor else None,
    )

    if posthog_span_processor:
        instrument_openai()
elif POSTHOG_AI_OBSERVABILITY_ENABLED:
    posthog_span_processor = configure_posthog_ai_observability(
        api_key=POSTHOG_API_KEY,
        ingest_host=POSTHOG_INGEST_HOST,
        environment=ENVIRONMENT,
        enabled=POSTHOG_AI_OBSERVABILITY_ENABLED,
    )

POSTHOG_LOGS_CONFIGURED = configure_posthog_logs(
    api_key=POSTHOG_API_KEY,
    ingest_host=POSTHOG_INGEST_HOST,
    environment=ENVIRONMENT,
    enabled=POSTHOG_LOGS_ENABLED,
    timeout_seconds=POSTHOG_LOG_TIMEOUT_SECONDS,
)


def posthog_middleware_extra_tags(request):
    user = getattr(request, "user", None)
    return {
        "environment": ENVIRONMENT,
        "authenticated": bool(user and user.is_authenticated),
        "user_is_staff": bool(user and user.is_authenticated and user.is_staff),
    }


def posthog_middleware_request_filter(request):
    if not POSTHOG_ENABLED:
        return False

    return not request.path.startswith(("/static/", "/__debug__/"))


POSTHOG_MW_EXTRA_TAGS = posthog_middleware_extra_tags
POSTHOG_MW_REQUEST_FILTER = posthog_middleware_request_filter

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "webpack_boilerplate",
    "widget_tweaks",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.google",
    "django_q",
    "django_filters",
    "django_extensions",
    "anymail",
    "mjml",
    "storages",
    "debug_toolbar",
    "django_structlog",
    # Custom
    "pages.apps.PagesConfig",
    "users.apps.UsersConfig",
    "jobs.apps.JobsConfig",
    "api.apps.ApiConfig",
    "utils.apps.UtilsConfig",
    "blog.apps.BlogConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "django.middleware.cache.UpdateCacheMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.cache.FetchFromCacheMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "hn_jobs.middleware.SentryMetricsMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "posthog.integrations.django.PosthogContextMiddleware",
    # "django_structlog.middlewares.RequestMiddleware",
]

ROOT_URLCONF = "hn_jobs.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR.joinpath("templates"))],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "hn_jobs.utils.site_metadata",
            ],
        },
    },
]

WSGI_APPLICATION = "hn_jobs.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": env.db_url(),
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR.joinpath("static/")

STATICFILES_DIRS = [
    BASE_DIR.joinpath("frontend/build"),
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_S3_REGION_NAME = "eu-east-1"
AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL")
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = f"hnjobs-{ENVIRONMENT}"
AWS_S3_FILE_OVERWRITE = False

MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

WEBPACK_LOADER = {
    "MANIFEST_FILE": BASE_DIR.joinpath("frontend/build/manifest.json"),
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication
AUTH_USER_MODEL = "users.CustomUser"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
SITE_ID = 1

LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"

ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_LOGIN_METHODS = {"username"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_FORMS = {
    "signup": "users.forms.CustomSignUpForm",
    "login": "users.forms.CustomLoginForm",
}
SOCIALACCOUNT_EMAIL_VERIFICATION = False
if not DEBUG:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = "hn_jobs.adapters.CustomSocialAccountAdapter"
SOCIALACCOUNT_PROVIDERS = {}

GITHUB_CLIENT_ID = env("GITHUB_CLIENT_ID", default="")
if GITHUB_CLIENT_ID != "":
    SOCIALACCOUNT_PROVIDERS["github"] = {
        "VERIFIED_EMAIL": True,
        "EMAIL_AUTHENTICATION": True,
        "AUTO_SIGNUP": True,
        "APP": {
            "client_id": env("GITHUB_CLIENT_ID"),
            "secret": env("GITHUB_CLIENT_SECRET"),
        },
        "SCOPE": [
            "user",
            "repo",
            "read:org",
        ],
    }

GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET", default="")
if GOOGLE_CLIENT_ID != "":
    SOCIALACCOUNT_PROVIDERS["google"] = {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_PKCE_ENABLED": True,
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID"),
            "secret": env("GOOGLE_CLIENT_SECRET"),
        },
        "AUTO_SIGNUP": True,
        "EMAIL_AUTHENTICATION": True,
    }

Q_CLUSTER = {
    "name": "hn_jobs-q",
    "timeout": 3600,  # 1 hour
    "retry": 4800,  # 80 minutes
    "workers": 4,
    "max_attempts": 2,
    "redis": env("REDIS_URL"),
    "error_reporter": {},
}

OPENAI_API_KEY = env("OPENAI_API_KEY")
OPENAI_JOB_EXTRACTION_MODEL = env("OPENAI_JOB_EXTRACTION_MODEL", default="gpt-5.4-nano")
OPENAI_PAGE_CONTEXT_EXTRACTION_MODEL = env(
    "OPENAI_PAGE_CONTEXT_EXTRACTION_MODEL",
    default=OPENAI_JOB_EXTRACTION_MODEL,
)
OPENAI_SALARY_EXTRACTION_MODEL = env("OPENAI_SALARY_EXTRACTION_MODEL", default="gpt-5-nano")
OPENAI_EMBEDDING_MODEL = env("OPENAI_EMBEDDING_MODEL", default="text-embedding-3-small")

JINA_READER_API_KEY = env("JINA_READER_API_KEY", default="")
JINA_READER_ENDPOINT = env("JINA_READER_ENDPOINT", default="https://r.jina.ai/")
JINA_READER_MAX_TOKENS = env.int("JINA_READER_MAX_TOKENS", default=4000)
JINA_READER_TIMEOUT_SECONDS = env.int("JINA_READER_TIMEOUT_SECONDS", default=30)
JINA_READER_CONTEXT_MAX_CHARS = env.int("JINA_READER_CONTEXT_MAX_CHARS", default=12000)

ANYMAIL = {
    "MAILGUN_API_KEY": env("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": "mg.gettjalerts.com",
}
DEFAULT_FROM_EMAIL = "TJ Alerts <rasul@gettjalerts.com>"
SERVER_EMAIL = "TJ Alerts <error@gettjalerts.com>"

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "mailhog"  # Use the service name from docker-compose
    EMAIL_PORT = 1025
    EMAIL_USE_TLS = False
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""
else:
    if env("MAILGUN_API_KEY", default="") == "":
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    else:
        EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"

API_TOKEN = env("API_TOKEN")
BUTTONDOWN_API_TOKEN = env("BUTTONDOWN_API_TOKEN")

MJML_BACKEND_MODE = "httpserver"
MJML_HTTPSERVERS = [
    {
        "URL": "https://api.mjml.io/v1/render",
        "HTTP_AUTH": ("8f8a2979-751d-4f54-b1fa-eced8024a3b7", env("MJML_SECRET")),
    }
]

if SENTRY_DSN:
    Q_CLUSTER["error_reporter"]["sentry"] = {"dsn": SENTRY_DSN}
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=ENVIRONMENT,
        release=SENTRY_RELEASE or None,
        send_default_pii=SENTRY_SEND_DEFAULT_PII,
        traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
        profile_session_sample_rate=SENTRY_PROFILE_SESSION_SAMPLE_RATE,
        profile_lifecycle="trace",
        enable_logs=SENTRY_ENABLE_LOGS,
        enable_metrics=SENTRY_ENABLE_METRICS,
        before_send_log=enrich_sentry_log,
        before_send_metric=enrich_sentry_metric,
        auto_session_tracking=True,
        stream_gen_ai_spans=True,
        integrations=[
            DjangoIntegration(),
            RedisIntegration(),
            LoggingIntegration(
                level=SENTRY_LOG_LEVEL,
                event_level=None,
                sentry_logs_level=None,
            ),
        ],
        attach_stacktrace=True,
        include_local_variables=True,
    )

INTERNAL_IPS = [
    "127.0.0.1",
]

HEALTHCHECKS_HOST = "https://healthchecks.cr.lvtd.dev/ping"


def extract_from_record(logger, name, event_dict):
    """
    Extract thread name and add them to the event dict.
    """
    record = event_dict["_record"]
    event_dict["thread_id"] = record.thread
    return event_dict


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(levelname)s %(message)s"},
        "verbose": {"format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"},
        "json": {"format": "%(message)s"},
        "json_formatter": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processors": [
                extract_from_record,
                structlog.stdlib.ProcessorFormatter.remove_processors_meta,
                structlog.processors.JSONRenderer(),
            ],
        },
        "plain_console": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(),
        },
        "key_value": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.KeyValueRenderer(key_order=["timestamp", "level", "event", "logger"]),
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "plain_console",
            "level": "DEBUG",
        },
        "prod_console": {
            "class": "logging.StreamHandler",
            "formatter": "plain_console",
            "level": "DEBUG",
        },
        "json_console": {
            "class": "logging.StreamHandler",
            "formatter": "json_formatter",
            "level": "DEBUG",
        },
    },
    "loggers": {
        "django_structlog": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        # django.server can log some low-level logs, but also does log requests,
        # for some reason...
        "django.server": {
            "handlers": ["console"],
            "level": "CRITICAL",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",  # so we don't chunder 404s, etc
            "propagate": False,
        },
        "tjalerts": {
            "level": "DEBUG",
            "handlers": ["console"],
            "propagate": False,
        },
    },
}

if POSTHOG_LOGS_CONFIGURED:
    LOGGING["handlers"]["posthog_logs"] = {
        "class": "opentelemetry.sdk._logs.LoggingHandler",
        "level": POSTHOG_LOG_LEVEL,
    }
    LOGGING["loggers"]["tjalerts"]["handlers"].append("posthog_logs")
    LOGGING["loggers"]["django.request"]["handlers"].append("posthog_logs")

structlog_processors = [
    structlog.contextvars.merge_contextvars,
    structlog.stdlib.filter_by_level,
    structlog.processors.TimeStamper(fmt="iso"),
    structlog.stdlib.add_logger_name,
    structlog.stdlib.add_log_level,
    structlog.stdlib.PositionalArgumentsFormatter(),
    structlog.processors.StackInfoRenderer(),
    # structlog.processors.format_exc_info,
]

if SENTRY_DSN and SENTRY_ENABLE_LOGS:
    structlog_processors.append(partial(send_structlog_to_sentry, min_level=SENTRY_LOG_LEVEL))

if SENTRY_DSN:
    structlog_processors.append(
        SentryProcessor(
            event_level=logging.ERROR,
            level=logging.INFO,
            active=True,
            as_context=True,
            tag_keys="__all__",
            verbose=True,
        )
    )

if LOGFIRE_TOKEN:
    structlog_processors.append(logfire.StructlogProcessor())

structlog_processors.extend(
    [
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ]
)

structlog.configure(
    processors=structlog_processors,
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)


ADMIN_KEY = env("ADMIN_KEY")
